server:
  port: 80

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  # thymeleaf模板引擎配置
  thymeleaf:
    # 缓存
    cache: false
    # 编码格式
    encoding: GB18030
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cuit.shop.entity

#showSql
logging:
  level:
    cuit:
      shop:
        mapper : debug


